### ISSUE TITLE
Bind keys with no modifiers

### ISSUE THREAD

**Issue by Max1Truc** [Object905/bindkey#1]
Hello @Object905,

I'm trying to run this code:
```rust
extern crate bindkey;

use bindkey::*;


fn main() {
    let mut storage = CallbackStorage::new();

    // Notice the `vec![]` to bring no modifier
    let key_a = HotKey::new(keysym::XK_a, vec![], TriggerOn::Press);
    storage.add(&key_a, pressed);

    start(storage);
}

fn pressed() {
  println!("Key \"a\" pressed");
}
```
However, that's not working and it throws this error:
```error
X Error of failed request:  BadAccess (attempt to access private resource denied)
  Major opcode of failed request:  33 (X_GrabKey)
  Serial number of failed request:  10
  Current serial number in output stream:  89
```

How could I bind a key with no modifiers using your library?

**Comment by Object905** [comment]
You can't. Also you can't bind button combinations that are already taken by your system (wm keyboard manager for example). Because this library uses [XGrabKey](https://tronche.com/gui/x/xlib/input/XGrabKey.html) as per documentation: If some other client has issued a XGrabKey() with the same key combination on the same window, a BadAccess error results. 

I don't really know how to solve it, but I can propose a heavier alternative, maybe it will suit your needs. Use [winit](https://github.com/rust-windowing/winit) and make invisible window, listen for [DeviceEvent](https://docs.rs/winit/0.20.0-alpha3/winit/event/enum.DeviceEvent.html), and your program is basically a key logger. Then match the buttons you want. Also since winit is cross-platform this "key logger" will be cross-platform as well.
